export const TEAM_NAME_ES: Record<string, string> = {
  'Mexico': 'México',
  'South Africa': 'Sudáfrica',
  'South Korea': 'Corea del Sur',
  'Czechia': 'República Checa',
  'Canada': 'Canadá',
  'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
  'Qatar': 'Catar',
  'Switzerland': 'Suiza',
  'Brazil': 'Brasil',
  'Morocco': 'Marruecos',
  'Haiti': 'Haití',
  'Scotland': 'Escocia',
  'USA': 'Estados Unidos',
  'Paraguay': 'Paraguay',
  'Australia': 'Australia',
  'Turkiye': 'Turquía',
  'Germany': 'Alemania',
  'Curacao': 'Curazao',
  'Ivory Coast': 'Costa de Marfil',
  'Ecuador': 'Ecuador',
  'Netherlands': 'Países Bajos',
  'Japan': 'Japón',
  'Sweden': 'Suecia',
  'Tunisia': 'Túnez',
  'Iran': 'Irán',
  'New Zealand': 'Nueva Zelanda',
  'Belgium': 'Bélgica',
  'Egypt': 'Egipto',
  'Spain': 'España',
  'Cape Verde': 'Cabo Verde',
  'Saudi Arabia': 'Arabia Saudí',
  'Uruguay': 'Uruguay',
  'France': 'Francia',
  'Senegal': 'Senegal',
  'Iraq': 'Irak',
  'Norway': 'Noruega',
  'Argentina': 'Argentina',
  'Algeria': 'Argelia',
  'Austria': 'Austria',
  'Jordan': 'Jordania',
  'Portugal': 'Portugal',
  'DR Congo': 'RD Congo',
  'Uzbekistan': 'Uzbekistán',
  'Colombia': 'Colombia',
  'England': 'Inglaterra',
  'Croatia': 'Croacia',
  'Ghana': 'Ghana',
  'Panama': 'Panamá',
};

export const STATIC_WC2026_TEAMS = [
  // CONMEBOL
  { id: 'ARG', name: 'Argentina', short_name: 'ARG', api_id: 6, group_name: null },
  { id: 'BRA', name: 'Brasil', short_name: 'BRA', api_id: 5, group_name: null },
  { id: 'COL', name: 'Colombia', short_name: 'COL', api_id: 31, group_name: null },
  { id: 'ECU', name: 'Ecuador', short_name: 'ECU', api_id: 113, group_name: null },
  { id: 'URU', name: 'Uruguay', short_name: 'URU', api_id: 17, group_name: null },
  { id: 'VEN', name: 'Venezuela', short_name: 'VEN', api_id: 97, group_name: null },
  { id: 'CHI', name: 'Chile', short_name: 'CHI', api_id: 98, group_name: null },
  { id: 'PAR', name: 'Paraguay', short_name: 'PAR', api_id: null, group_name: null },
  // CONCACAF
  { id: 'USA', name: 'Estados Unidos', short_name: 'USA', api_id: 1, group_name: null },
  { id: 'MEX', name: 'México', short_name: 'MEX', api_id: 16, group_name: null },
  { id: 'CAN', name: 'Canadá', short_name: 'CAN', api_id: 94, group_name: null },
  { id: 'PAN', name: 'Panamá', short_name: 'PAN', api_id: 89, group_name: null },
  { id: 'HON', name: 'Honduras', short_name: 'HON', api_id: 80, group_name: null },
  { id: 'CRC', name: 'Costa Rica', short_name: 'CRC', api_id: 273, group_name: null },
  // UEFA
  { id: 'ESP', name: 'España', short_name: 'ESP', api_id: 9, group_name: null },
  { id: 'FRA', name: 'Francia', short_name: 'FRA', api_id: 2, group_name: null },
  { id: 'ENG', name: 'Inglaterra', short_name: 'ENG', api_id: 10, group_name: null },
  { id: 'GER', name: 'Alemania', short_name: 'GER', api_id: 25, group_name: null },
  { id: 'POR', name: 'Portugal', short_name: 'POR', api_id: 27, group_name: null },
  { id: 'NED', name: 'Países Bajos', short_name: 'NED', api_id: 33, group_name: null },
  { id: 'BEL', name: 'Bélgica', short_name: 'BEL', api_id: null, group_name: null },
  { id: 'ITA', name: 'Italia', short_name: 'ITA', api_id: 768, group_name: null },
  { id: 'CRO', name: 'Croacia', short_name: 'CRO', api_id: 3, group_name: null },
  { id: 'SUI', name: 'Suiza', short_name: 'SUI', api_id: 15, group_name: null },
  { id: 'AUT', name: 'Austria', short_name: 'AUT', api_id: 775, group_name: null },
  { id: 'DEN', name: 'Dinamarca', short_name: 'DEN', api_id: 21, group_name: null },
  { id: 'SRB', name: 'Serbia', short_name: 'SRB', api_id: 14, group_name: null },
  { id: 'TUR', name: 'Turquía', short_name: 'TUR', api_id: 761, group_name: null },
  { id: 'POL', name: 'Polonia', short_name: 'POL', api_id: 24, group_name: null },
  { id: 'SCO', name: 'Escocia', short_name: 'SCO', api_id: 1178, group_name: null },
  { id: 'ALB', name: 'Albania', short_name: 'ALB', api_id: null, group_name: null },
  { id: 'CZE', name: 'República Checa', short_name: 'CZE', api_id: null, group_name: null },
  { id: 'SVN', name: 'Eslovenia', short_name: 'SVN', api_id: null, group_name: null },
  { id: 'UKR', name: 'Ucrania', short_name: 'UKR', api_id: null, group_name: null },
  // CAF
  { id: 'MAR', name: 'Marruecos', short_name: 'MAR', api_id: 45, group_name: null },
  { id: 'SEN', name: 'Senegal', short_name: 'SEN', api_id: 34, group_name: null },
  { id: 'EGY', name: 'Egipto', short_name: 'EGY', api_id: 36, group_name: null },
  { id: 'NGA', name: 'Nigeria', short_name: 'NGA', api_id: 37, group_name: null },
  { id: 'CMR', name: 'Camerún', short_name: 'CMR', api_id: 38, group_name: null },
  { id: 'CIV', name: 'Costa de Marfil', short_name: 'CIV', api_id: 46, group_name: null },
  { id: 'GHA', name: 'Ghana', short_name: 'GHA', api_id: 39, group_name: null },
  { id: 'ALG', name: 'Argelia', short_name: 'ALG', api_id: 35, group_name: null },
  { id: 'RSA', name: 'Sudáfrica', short_name: 'RSA', api_id: 186, group_name: null },
  // AFC
  { id: 'JPN', name: 'Japón', short_name: 'JPN', api_id: 26, group_name: null },
  { id: 'KOR', name: 'Corea del Sur', short_name: 'KOR', api_id: 732, group_name: null },
  { id: 'KSA', name: 'Arabia Saudí', short_name: 'KSA', api_id: 146, group_name: null },
  { id: 'AUS', name: 'Australia', short_name: 'AUS', api_id: null, group_name: null },
  { id: 'IRN', name: 'Irán', short_name: 'IRN', api_id: 796, group_name: null },
  { id: 'IRQ', name: 'Irak', short_name: 'IRQ', api_id: 164, group_name: null },
  { id: 'JOR', name: 'Jordania', short_name: 'JOR', api_id: 163, group_name: null },
  { id: 'UZB', name: 'Uzbekistán', short_name: 'UZB', api_id: null, group_name: null },
  // OFC
  { id: 'NZL', name: 'Nueva Zelanda', short_name: 'NZL', api_id: null, group_name: null },
] as const;
